/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UnySpotlightSearch {
        "closeOnEscape": boolean;
        "keyboardShortcuts": string;
        "url": string;
    }
}
declare global {
    interface HTMLUnySpotlightSearchElement extends Components.UnySpotlightSearch, HTMLStencilElement {
    }
    var HTMLUnySpotlightSearchElement: {
        prototype: HTMLUnySpotlightSearchElement;
        new (): HTMLUnySpotlightSearchElement;
    };
    interface HTMLElementTagNameMap {
        "uny-spotlight-search": HTMLUnySpotlightSearchElement;
    }
}
declare namespace LocalJSX {
    interface UnySpotlightSearch {
        "closeOnEscape"?: boolean;
        "keyboardShortcuts"?: string;
        "onActionSelected"?: (event: CustomEvent<any>) => void;
        "url"?: string;
    }
    interface IntrinsicElements {
        "uny-spotlight-search": UnySpotlightSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "uny-spotlight-search": LocalJSX.UnySpotlightSearch & JSXBase.HTMLAttributes<HTMLUnySpotlightSearchElement>;
        }
    }
}
